# Generated by Django 4.2.7 on 2025-09-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AkaBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refactorlog',
            fields=[
                ('operationkey', models.CharField(db_column='OperationKey', max_length=36, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '__RefactorLog',
                'managed': False,
            },
        ),
    ]
